### ISSUE TITLE
New git hook to trigger read-the-docs buils

### ISSUE THREAD

**Issue by jobec** [infobloxopen/infoblox-netmri#4]
This repo should get a new hook to trigger a read-the-docs build.

Post Commit Hook:
curl -X POST https://readthedocs.org/build/infoblox-netmri

@johnbelamaric : If you create a read-the-docs account, I'll make you maintainer

**Comment by infobloxopen** [comment]
I created an "infobloxopen" read-the-docs account. Thanks for contributing!

**Comment by jobec** [comment]
Account added.
After the commit hook is in place, docs should get updated on commit

**Comment by infobloxopen** [comment]
Ok, I added the web hook in GitHub. Looks like it's working now. Thanks.
