### ISSUE TITLE
All requests fail when authenticated session becomes invalid

### ISSUE THREAD

**Issue by jobec** [infobloxopen/infoblox-netmri#7]
With long standing connections (like within a web application on a webserver) it's possible the authenticated session with netmri times out, causing all API requests to fail.

**Comment by jobec** [comment]
Relevant part of the traceback
```  
File "/opt/lib/python3.4/site-packages/infoblox_netmri/__init__.py", line 158, in api_request
    return self._make_request(url=url, method="post", data=data)
  File "/opt/lib/python3.4/site-packages/infoblox_netmri/__init__.py", line 94, in _make_request
    r.raise_for_status()
  File "/opt/lib/python3.4/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://infoblox-netmri/api/3/devices/search
```

**Comment by johnbelamaric** [comment]
Ok, so we need to re-try authentication then repeat the request if auth succeeds, in the event of a 401 or 403.

**Comment by jobec** [comment]
Maybe move the call to ``self._authenticate()`` from ``__init__`` to ``api_request``? Then keep a pointer somewhere to see if authenticaiton has happened already or not.

``show()`` and ``delete()`` can then build on top of ``api_request()`` and that way ``_make_request()`` becomes obsolete.
